name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
    env:
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1:8000
        DEBUG_MODE: True
    run: |
      python -m pip install --upgrade pip
      pip install django
      pip install django-cryptography
      pip install requests
      pip install python-decouple
      pip install virtualenv
      
    - name: Configure Environment
      run: |
        virtualenv env
        python manage.py makemigrations LegacySite
        python manage.py makemigrations
        python manage.py migrate

    - name: Django Testing
      run: |
        python3 manage.py test
